/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-07-02 01:56:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("f:url", org.seasar.struts.taglib.S2Functions.class, "url", new Class[] {java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/view/common/common.jsp", Long.valueOf(1275625666000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<title>Welcome to Super Agile Struts</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${f:url('/css/sa.css')}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0, false));
      out.write("\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<h1>Welcome to Super Agile Struts Tutorial</h1>\r\n");
      out.write("\r\n");
      out.write("<p>\r\n");
      out.write("Tomcatの設定はお済みですか?<br />\r\n");
      out.write("まだなら、\r\n");
      out.write("<a href=\"http://sastruts.seasar.org/fileReference.html#server\">conf/server.xml</a>\r\n");
      out.write("をリンクの指示に従って修正してください。\r\n");
      out.write("</p>\r\n");
      out.write("<p>\r\n");
      out.write("文字化けになる場合も上記の設定を確認してください。\r\n");
      out.write("</p>\r\n");
      out.write("<p>\r\n");
      out.write("アクションフォームやDtoでHOT deployがうまくいかない場合は\r\n");
      out.write("<a href=\"http://sastruts.seasar.org/fileReference.html#context\">conf/context.xml</a>\r\n");
      out.write("の設定を確認してください。\r\n");
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("<ul>\r\n");
      out.write("<li><a href=\"http://sastruts.seasar.org/index.html\">SAStrutsのサイト</a></li>\r\n");
      out.write("<li><a href=\"add/\">足し算</a></li>\r\n");
      out.write("<li><a href=\"session/\">セッションスコープのアクションフォーム</a></li>\r\n");
      out.write("<li><a href=\"redirect/\">他のサイトを表示</a></li>\r\n");
      out.write("<li><a href=\"foreach/\">繰り返し</a></li>\r\n");
      out.write("<li><a href=\"foreachButton/\">ボタンを使った繰り返し</a></li>\r\n");
      out.write("<li><a href=\"nestedForeach/\">ネストした繰り返し</a></li>\r\n");
      out.write("<li><a href=\"foreachUpdate/\">更新可能な繰り返し</a></li>\r\n");
      out.write("<li><a href=\"nestedForeachUpdate/\">更新可能なネストした繰り返し</a></li>\r\n");
      out.write("<li><a href=\"validator/\">アノテーションを使った検証</a></li>\r\n");
      out.write("<li><a href=\"clientValidator/\">クライアントサイド検証</a></li>\r\n");
      out.write("<li><a href=\"select/\">選択リスト</a></li>\r\n");
      out.write("<li><a href=\"multiselect/\">複数選択リスト</a></li>\r\n");
      out.write("<li><a href=\"checkbox/\">チェックボックス</a></li>\r\n");
      out.write("<li><a href=\"multibox/\">複数選択可能なチェックボックス</a></li>\r\n");
      out.write("<li><a href=\"radio/\">ラジオボタン</a></li>\r\n");
      out.write("<li><a href=\"textarea/\">テキストエリア</a></li>\r\n");
      out.write("<li><a href=\"condition/1\">条件(id=1)</a></li>\r\n");
      out.write("<li><a href=\"condition/2\">条件(id=2)</a></li>\r\n");
      out.write("<li><a href=\"token/\">ボタンの2度押し対策</a></li>\r\n");
      out.write("<li><a href=\"upload/\">ファイルアップロード</a></li>\r\n");
      out.write("<li><a href=\"download/\">ファイルダウンロード</a></li>\r\n");
      out.write("<li><a href=\"tiles/\">レイアウト</a></li>\r\n");
      out.write("<li><a href=\"protect/\">保護されたページ</a></li>\r\n");
      out.write("<li><a href=\"logout/\">ログアウト</a></li>\r\n");
      out.write("<li><a href=\"ajax/\">Ajax</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
